name: CI/CD Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Cache Poetry virtualenv
        uses: actions/cache@v6
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --no-root

      - name: Security Scan (Dependencies)
        run: poetry run pip install pip-audit && poetry run pip-audit
        continue-on-error: true

      - name: Check formatting with Ruff
        run: poetry run ruff format --check .

      - name: Lint with Ruff
        run: poetry run ruff check .

      - name: Type checking with Pyright
        run: poetry run pyright

#      - name: Run Unit Tests
#        run: poetry run pytest -m "not remote"
